### ISSUE TITLE
Zplugin update fails if only loaded on interactive session

### ISSUE THREAD

**Issue by comfortablynick** [r-darwish/topgrade#291]
I am a zplugin user, and I've noticed that the update in topgrade fails, whether I'm inside ZSH or not. Currently, I'm primarily using fish, but I switch to Zsh regularly.

```
―― 10:31:33 - zplugin ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
zsh:1: command not found: zplugin
```
I noticed that it succeeds if I remove this line from .zshrc:
```zsh
[[ $- != *i* ]] && return
```
Is there any way to make this work with topgrade? I thought having the above guard in the rc file was a good practice, but maybe it's not needed?

Thanks!

**Comment by r-darwish** [comment]
I'm not sure why is this related. Topgrade runs zsh and source the `~/.zplugin` file. Can you run `topgrade -n` and print the command?

**Comment by comfortablynick** [comment]
It doesn't show sourcing `~/.zplugin` here, but I'm not sure if it's doing anything else.
```
―― 12:51:17 - zplugin ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
Dry running: /usr/bin/zsh -c source /home/nick/.zshrc && zplugin self-update && zplugin update --all
```

**Comment by r-darwish** [comment]
I pushed a branch called `zsh-interactive`. Can you please check if it resolves your issue?

**Comment by r-darwish** [comment]
@gkze can you also try this branch? Perhaps it is relevant to your issue as well

**Comment by r-darwish** [comment]
@cybercussion maybe for you as well

**Comment by comfortablynick** [comment]
> I pushed a branch called `zsh-interactive`. Can you please check if it resolves your issue?
Yes, that fixes it!

**Comment by r-darwish** [comment]
I'll release a hotfix then. Hopefully it will help the others as well

**Comment by r-darwish** [comment]
Fixed in 108ef602034d656e6523845dbbce4d129ff1a94c and released in v3.7.1

**Comment by gkze** [comment]
It works now - thank you!

**Comment by comfortablynick** [comment]
My zplugin update is still failing with the latest binary and latest from cargo. Interestingly, when I install the `zsh-interactive` branch using cargo, it works fine. Is anyone else experiencing this?
